apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: disk-inventory
spec:
  selector:
    matchLabels:
      app: disk
      daemon: inventory
  template:
    metadata:
      name: disk-inventory
      labels:
        app: disk
        daemon: inventory
    spec:
      serviceAccount: disk-inventory
      nodeSelector:
        diskInventory: "true"
      containers:
      - name:  disk-inventory
        image: quay.io/polargeospatialcenter/disk-inventory
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
          - name: udev
            mountPath: /run/udev
      volumes:
        - name: udev
          hostPath:
            path: /run/udev
